### ISSUE TITLE
✨ feat : detail page

### ISSUE THREAD

**Issue by z1zonemoi** [codestates-seb/seb40_main_010#123]
## 📝 Github Issue
Issue 설명

detail page

## ✔️ Check List
> 이슈 체크리스트

- [x] main page와 연결
- [x] 외부 api 사용 -> json-server 데이터 추가해서 연결
- [x] 구조(ui)
- [x] react-slick(ui)

**Comment by mozzi327** [comment]
고생하셨습니다!! :\
