### ISSUE TITLE
Mail 기능 구현

### ISSUE THREAD

**Issue by LeeGoh** [codestates-seb/seb40_main_010#234]
## 📝 Github Issue
Search 기능 구현

## ✔️ Check List
> 이슈 체크리스트

### 예약 내역 메일 전송
- [x] Controller(@ POST MAPPING)
- [x] Service(MailSender)

### 기능 구현 테스트
- [x] JUnit5 Testing
- [x] ...

**Comment by mozzi327** [comment]
고생하셨습니다!!
