### ISSUE TITLE
Place 기능 구현

### ISSUE THREAD

**Issue by LimJaeminZ** [codestates-seb/seb40_main_010#80]
## 📝 Github Issue
Issue 설명
Place Table 기능 구현 

## ✔️ Check List
> 이슈 체크리스트

- [x] 장소 생성 
- [x] 장소 이미지 생성 
- [x] 장소 카테고리 매핑
- [x] 장소 검색
- [x] 장소 수정
- [x] 장소 삭제

**Comment by mozzi327** [comment]
고생하셨습니다!! :\
